[package]
name = "fund"
version = "0.7.0"
authors = ["Christopher Leggett <leggettc18@gmail.com>"]

[dependencies]
dirs = "1.0.4"
clap = "~2.32"

[dependencies.libfund]
path = "libfund"

[workspace]
members = [
    "libfund",
]
